"""Actor graph CRUD — persisted as JSON-LD in the workspace."""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from datetime import datetime, timezone

from fastapi import APIRouter, HTTPException, Request
from pydantic import BaseModel

from studio_api.api.v1.deps import require_permission
from studio_api.config import get_settings

router = APIRouter()


# ── Graph file lock ───────────────────────────────────────────────────────────


@dataclass
class GraphLock:
    """Tracks which client has a graph file open for editing."""

    path: str
    client_id: str    # client-provided UUID (unique per app instance, not per user)
    client_host: str  # IP of the machine that opened the file
    client_label: str # human-readable app name (e.g. "Cantica Studio", "VS Code Extension")
    opened_at: str    # ISO-8601 UTC timestamp


def _locks(request: Request) -> dict[str, GraphLock]:
    return request.app.state.graph_locks  # type: ignore[no-any-return]


class LockRequest(BaseModel):
    path: str
    client_id: str      # required — UUID generated by the client at startup
    client_label: str = ""


class UnlockRequest(BaseModel):
    path: str
    client_id: str


@router.get("/lock", dependencies=[require_permission("graph:read")])
def list_locks(request: Request) -> list[dict]:
    """Return all currently open graph files and who has them locked."""
    return [asdict(lock) for lock in _locks(request).values()]


@router.post("/lock", dependencies=[require_permission("graph:write")])
def claim_lock(body: LockRequest, request: Request) -> dict:
    """Claim exclusive write access to a graph file.

    A client may re-claim a lock it already holds (idempotent — refreshes opened_at).
    Returns 409 when a *different* client already has the file open.
    """
    locks = _locks(request)
    existing = locks.get(body.path)
    client_host = (request.client.host if request.client else "unknown")

    if existing is not None and existing.client_id != body.client_id:
        raise HTTPException(
            status_code=409,
            detail={
                "message": f"File already open by another client",
                "lock": asdict(existing),
            },
        )

    locks[body.path] = GraphLock(
        path=body.path,
        client_id=body.client_id,
        client_host=client_host,
        client_label=body.client_label,
        opened_at=datetime.now(timezone.utc).isoformat(),
    )
    return {"locked": True, **asdict(locks[body.path])}


@router.delete("/lock", dependencies=[require_permission("graph:write")])
def release_lock(body: UnlockRequest, request: Request) -> dict:
    """Release a graph file lock held by this client.

    A no-op if the file is not locked. Returns 403 if a different client holds the lock.
    """
    locks = _locks(request)
    existing = locks.get(body.path)

    if existing is None:
        return {"locked": False, "path": body.path}

    if existing.client_id != body.client_id:
        raise HTTPException(
            status_code=403,
            detail={
                "message": "Cannot release a lock held by a different client",
                "lock": asdict(existing),
            },
        )

    del locks[body.path]
    return {"locked": False, "path": body.path}


# ── Graph CRUD ────────────────────────────────────────────────────────────────


class GraphPayload(BaseModel):
    data: dict


@router.get("", dependencies=[require_permission("graph:read")])
def load_graph() -> dict:
    """Return the actor graph JSON-LD from the workspace file."""
    path = get_settings().graph_path
    if not path.exists():
        return _empty_graph()
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc


@router.put("", dependencies=[require_permission("graph:write")])
def save_graph(payload: GraphPayload) -> dict:
    """Persist the actor graph JSON-LD to the workspace file."""
    path = get_settings().graph_path
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(payload.data, indent=2, ensure_ascii=False), encoding="utf-8")
        return {"status": "saved"}
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc


def _empty_graph() -> dict:
    return {
        "@context": {
            "@vocab": "https://cantica.dev/studio/",
            "schema": "http://schema.org/",
            "name": "schema:name",
        },
        "@type": "ActorGraph",
        "@id": "urn:cantica:studio:graph:default",
        "name": "New Workflow",
        "actors": [],
        "edges": [],
    }
